<?php

function fileupload_schema() {
  $schema['fileupload'] = array(
    'fields' => array(
      'id'=>array(
        'type'=>'serial',
        'not null' => TRUE,
      ),
      'employee_name'=>array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'document_name'=>array(
        'type' => 'varchar',
        'length' => 40,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
  );

  return $schema;

}